FotofooBatchBundle:
    resource: "@FotofooBatchBundle/Controller/"
    type:     annotation
    prefix:   /batch

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

FotofooBatchBundle:
    resource: "@FotofooBatchBundle/Controller/"
    type:     annotation
    prefix:   /batch

SwiftImageBundle:
    resource: "@SwiftImageBundle/Controller/"
    type:     annotation
    prefix:   /image

_assetic:
    resource: .
    type:     assetic

_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml
