FotofooBatchBundle:
    resource: "@FotofooBatchBundle/Controller/"
    type:     annotation
    prefix:   /batch

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

FotofooBatchBundle:
    resource: "@FotofooBatchBundle/Controller/"
    type:     annotation
    prefix:   /batch

SwiftImageBundle:
    resource: "@SwiftImageBundle/Controller/"
    type:     annotation
    prefix:   /image
